### ISSUE TITLE
Login page refreshes after device orientation change

### ISSUE THREAD

**Issue by mmc20520** [flex3r/DankChat#238] opened 2022-03-03 15:35 UTC
Login page refreshes after device orientation change, therefore we have to manually restore webview states after rotation

Before rotation:
<img width="287" alt="Screen Shot 2022-03-03 at 11 33 38 PM" src="https://user-images.githubusercontent.com/100833575/156597398-a6000113-6b71-4a43-b9c1-cc372da539fb.png">

After rotation:

<img width="624" alt="Screen Shot 2022-03-03 at 11 33 46 PM" src="https://user-images.githubusercontent.com/100833575/156597427-56f200b2-ec36-4e52-a9c9-de4ba6ffff7c.png">

I was testing on v3.0.8 on Android 10

**Comment by flex3r** [comment] 2022-03-03 19:42
Basically a duplicate of https://github.com/flex3r/DankChat/issues/218. The WebView provides methods to save/restore state, but these do not include display data. Therefore it would still trigger a refresh.  
The only other way would be to manually handle configuration changes which I am not going to do as it is a outdated and very bad practice.  
Also, I don't think this is as much of an issue. At some point I want to migrate the login to Chrome custom tabs anyways, which will fix this issue.

**Closed by flex3r** 2022-03-03 19:42 UTC
Labels: wontfix
