### ISSUE TITLE
Version 3.1.7 crash at start

### ISSUE THREAD

**Issue by Osahashi** [flex3r/DankChat#247] opened 2022-04-05 20:26 UTC
the current version 3.1.7 crashes immediately when I start the app on my Realme x2 Pro, I have already cleared the cache without success. Would hate to reinstall or reset because then all my settings are gone.

when I start it comes the message: "DankChat failed to start several times."

**Comment by FlowMo7** [comment] 2022-04-06 08:13
Am facing this issue as well, and can reproduce on a clean install on Android 12 and Android 11.

(obfuscated) stacktrace from a clean install on Android 11:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flxrs.dankchat, PID: 11363
    java.lang.NoSuchMethodError: No static method newKeySet()Lj$/util/concurrent/ConcurrentHashMap$KeySetView; in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in /data/app/~~OiMJcJwxTGCdNf-L9xvKtQ==/com.flxrs.dankchat-6OJ_ui7DomSSIMWXmFqcJA==/base.apk!classes2.dex)
        at a3.b.<init>(Unknown Source:59)
        at m2.a$i.get(:41)
        at j5.a.get(Unknown Source:13)
        at m2.a$i.get(:42)
        at j5.a.get(Unknown Source:13)
        at m2.a$m$a.get(Unknown Source:178)
        at g5.b$a.e(:3)
        at androidx.lifecycle.a.d(:4)
        at androidx.lifecycle.a.a(Unknown Source:10)
        at g5.b.a(Unknown Source:14)
        at androidx.lifecycle.s0.a(:1)
        at g5.b.b(Unknown Source:0)
        at androidx.lifecycle.r0.b(:5)
        at androidx.lifecycle.r0.a(Unknown Source:17)
        at androidx.lifecycle.q0.getValue(:1)
        at com.flxrs.dankchat.main.MainActivity.onCreate(:14)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Activity.performCreate(Activity.java:8175)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

(although, seems that this might already be fixed for `3.1.8` as of https://github.com/flex3r/DankChat/commit/17bb70316c674fc0952b9b575d2990addc2f8a5b)

**Comment by Osahashi** [comment] 2022-04-06 10:09
Thanks for the confirmation and the data, so far I do not see 3.1.8 in the PlayStore, but I guess that's just a matter of time :)

**Comment by flex3r** [comment] 2022-04-06 13:51
Yes it's fixed in 17bb70316c674fc0952b9b575d2990addc2f8a5b but Google is giving me trouble and actually rejected the version :/ 
The reasons they are giving make no sense but I know an appeal will take well over a week. I'm trying my luck by uploading the same version again and hoping for an actual reviewer with a brain.

**Comment by flex3r** [comment] 2022-04-06 13:52
For now, opting out of the beta might be the best choice

**Comment by Osahashi** [comment] 2022-04-06 14:51
Because of the crash I looked for the old version, but had to realize that this is not so easy, at https://install.appcenter.ms/users/flex3r/apps/dankchat/distribution_groups/public there were no backups for download since Sep 20, 2021 and you always offer only a debug APK as a download here. Also at F-Droid is always only the current version available, but not the old version. Other download sites also offer only versions from 2021 as download.

I have not tried it so far, the "Debug APK" is the same version as in the PlayStore? Or how is it different? Since it is debug, I assume it is for debugging and shows more data, records with log etc

**Comment by flex3r** [comment] 2022-04-06 17:23
The only difference between the debug and release one is that the debug version is not signed. Apart from that they are identical, so you should be able to use it. Unfortunately you can't just install it over the play store version because of the signing differences, so existing settings will be lost :/

**Comment by flex3r** [comment] 2022-04-07 12:18
3.1.9 with a fix for the crash just got approved and should be available shortly 👍

**Closed by flex3r** 2022-04-07 12:18 UTC
