### ISSUE TITLE
Data upload error. DankChatBadges

### ISSUE THREAD

**Issue by jaimecy** [flex3r/DankChat#512] opened 2023-05-15 18:01 UTC
Hello. Another thing that happens to me. I'm using Dankchat on an Android emulator for Windows, Bluestack, and I get this trap message. In addition, the icons of each channel in which I am subscribed do not appear. Everything else works fine. Greetings and thank you.
![Captura de pantalla 2023-05-15 195144](https://github.com/flex3r/DankChat/assets/4126584/de511203-40ac-4455-a442-c1f4854c818d)
![Captura de pantalla 2023-05-15 131241](https://github.com/flex3r/DankChat/assets/4126584/fd9e84ea-ac56-405c-a495-50ace30d6e9e)

**Comment by flex3r** [comment] 2023-05-15 18:06
Hi, looks like your emulator can't connect to my domain properly. Can you try to open this website on your emulator and check if you have the same connection issues? https://flxrs.com 
I checked my configuration and can't immediately spot any server issues on my end..

**Comment by jaimecy** [comment] 2023-05-15 18:13
![Screenshot_2023 05 15_20 10 28 952](https://github.com/flex3r/DankChat/assets/4126584/db3c85c6-94b2-4127-a74d-f1cf560d2d28)

**Comment by flex3r** [comment] 2023-05-15 19:16
Alright, now press the warning sign in the top left corner and let's see the error chrome is reporting. Seems like there is a certificate issue.

**Comment by jaimecy** [comment] 2023-05-15 19:22
Sorry!!
![Captura de pantalla 2023-05-15 212029](https://github.com/flex3r/DankChat/assets/4126584/403c4171-5df4-4f79-bef8-5e55babb3f4a)
![Captura de pantalla 2023-05-15 212038](https://github.com/flex3r/DankChat/assets/4126584/7eadce25-0345-413b-8b30-bc706286c991)
![Captura de pantalla 2023-05-15 212050](https://github.com/flex3r/DankChat/assets/4126584/1a3244a3-235c-4af5-bffb-cc8f5da8fb09)

**Comment by flex3r** [comment] 2023-05-15 19:40
I checked again and couldn't find any configuration issue. It could be a temporary error on your side that might fix itself in the next couple of days. If it doesn't please report back and I will take a look again.. Can't do much more as I do not have any issues on my end

**Comment by Yukarichan** [comment] 2023-05-15 21:04
Hi,
 I have the same error since a few days now. Emotes are not loading properly and every time I get the certificate error.
Same when I open the stated website.
I'm using an Android phone.

![Screenshot_20230515-225848_DankChat](https://github.com/flex3r/DankChat/assets/5430633/2336dbd7-e253-41f5-94a5-364697aaf0d9)
![Screenshot_20230515-230251_Chrome](https://github.com/flex3r/DankChat/assets/5430633/9a4722b7-729e-4e3a-8bf8-0c7d88059088)

**Comment by flex3r** [comment] 2023-05-16 09:32
@Yukarichan Out of curiosity what phone are you using and what Android version is it running?

**Comment by Yukarichan** [comment] 2023-05-16 10:03
The emotes are loading again now, I don't get the error anymore and I can access the website without the warning.

I'm using a Samsung Galaxy Note 8 with Android 9 currently.

**Comment by flex3r** [comment] 2023-05-16 10:40
That is good to hear, so that confirms that the issue is on Cloudflare. There are others experiencing the same issues, so let's wait on Cloudflare and see if they respond: https://community.cloudflare.com/t/google-trust-services-edge-certificate-not-trusted/509780

**Comment by jaimecy** [comment] 2023-05-16 11:10
Perfect, thanks!!! 
![Captura de pantalla 2023-05-16 130929](https://github.com/flex3r/DankChat/assets/4126584/e6f68adf-e2e4-4c67-86a3-903cf64f8977)

**Comment by flex3r** [comment] 2023-05-31 09:12
Hi @Yukarichan & @jaimecy, could you just quickly confirm that you are still able to use the app properly?
I have enabled my Cloudflare configuration again with a new certificate chain and want to make sure that it now works as expected

**Comment by jaimecy** [comment] 2023-05-31 09:33
Hello. It is working fine on Bluestack. Thank you. 
![Screenshot_2023 05 31_11 30 40 387](https://github.com/flex3r/DankChat/assets/4126584/aeda8c41-2c02-4a90-a74e-347ce17a4257)

**Comment by Yukarichan** [comment] 2023-05-31 12:17
So far everything looks fine :)
If I notice anything I'll come back to it, but seems like everything works normal 👍

**Comment by flex3r** [comment] 2023-05-31 12:18
Perfect, closing this then. Thanks for the help!

**Closed by flex3r** 2023-05-31 12:18 UTC
