### ISSUE TITLE
reading emotes & ignore word

### ISSUE THREAD

**Issue by AUTdany** [flex3r/DankChat#467] opened 2023-04-05 07:05 UTC
The app reading emotes even you set the setting ignore emotes if a user only text one emote...

and i cant ignore that "^"

android 13
pixel 5

**Comment by flex3r** [comment] 2023-04-07 11:32
Hm, when I enable the ignore emotes setting messages are not read out if a user only sends one emote. Perhaps I don't quite understand your issue, could you explain it in more detail?

**Comment by AUTdany** [comment] 2023-04-08 21:17
![image](https://user-images.githubusercontent.com/128122660/230742872-8adc32c4-01a4-4343-a5dc-efde3be158a9.png)

if someone write only one emote it will be reading by tts... if someone wrtie more than one emote tts doesnt read it out

**Comment by flex3r** [comment] 2023-04-09 17:53
Yeah, I cannot reproduce this unfortunately. For me the ignore emotes setting works as expected, no message is read out with either one emote or many..
Does this happen with a specific type of emote, e.g. a Twitch or 3rd party one? Any additional information would help me reproduce this issue.

**Comment by AUTdany** [comment] 2023-04-10 07:16
all emotes dosent matter wich one.. all of my emotes , if they user wrtie only one emote, that emote will read out by tts

i deinstal the app.. delte the cach and storage.. nothing help... the app will read out the emote if a viewer only post one

**Comment by AUTdany** [comment] 2023-04-11 09:45
so i did it again.. clear the cach and delte the storage.. NOW its working.. thanks for help sir <3

**Comment by flex3r** [comment] 2023-04-11 10:06
Nice that you were able to fix it! Closing this issue :)

**Closed by flex3r** 2023-04-11 10:06 UTC
