### ISSUE TITLE
Opens to a black screen.

### ISSUE THREAD

**Issue by TheBliTzzzzzz** [flex3r/DankChat#96] opened 2020-10-15 21:27 UTC
I open the app, and once I click either opt-in or opt-out to message history, the screen stays black. F-Droid version (2.2.5) is working fine.

App Store: Google Play Store
Version: 2.3.1
Phone: OnePlus 6

**Comment by TheBliTzzzzzz** [comment] 2020-10-15 21:39
Update: Just received v2.3.1 on F-Droid and it worked if I had previously used the app. However, if I had not, such as a fresh install, there was a black screen during setup.

**Comment by flex3r** [comment] 2020-10-16 09:19
Really weird issue, I've also received reviews from the play store with the same behaviour. For now I've reverted a recent update of the ConstraintLayout dependency. Apart from that I haven't made any changes that could cause this, I think

**Comment by flex3r** [comment] 2020-10-16 09:21
If you want to help, can you try to fresh install this debug apk https://github.com/flex3r/DankChat/releases/download/debug/DankChat-debug.apk?

**Comment by TheBliTzzzzzz** [comment] 2020-10-16 09:47
@flex3r Debug APK is working fine for me.

**Comment by flex3r** [comment] 2020-10-16 10:03
Sounds good, I uploaded a new release to the play store and it's awaiting review currently. I'll close this when the new version is out and you can confirm that the issue is fixed in the release version too.

**Comment by TheBliTzzzzzz** [comment] 2020-10-16 10:07
Great, will do.

**Comment by TheBliTzzzzzz** [comment] 2020-10-16 14:32
@flex3r Just installed through Google Play, and all seems to be fine. Thanks for the quick fix.

**Comment by flex3r** [comment] 2020-10-16 14:34
Cool, thanks for reporting this! (Fixed in b9c92a1e5c8d4e7cf74b59fff5001ea583f74d7f)

**Closed by flex3r** 2020-10-16 14:34 UTC
Labels: bug
